### ISSUE TITLE
fia_ts Mortar issue

### ISSUE THREAD

**Issue by Teizan0** [republic-of-folk/rof_addons#1]
![image](https://user-images.githubusercontent.com/31879365/79410929-bb0b0c80-7ff5-11ea-8700-fa1c0c1d099f.png)

Team leader equipped with HMG tripod rather than Mortar bipod.

(Or at least, I *think* it's fia_ts. I didn't keep an .original file.)

**Comment by Boberro** [comment]
Good catch
